GET https://localhost:5162/api/categorias

###

GET https://localhost:5162/api/categorias/2

###

POST https://localhost:5162/api/categorias
Content-Type: application/json
{
    "nombre": "Categoria de prueba"
}

###

PUT https://localhost:5162/api/categorias/16
Content-Type: application/json
{
    "nombre": "Categoria de prueba modificada"
}

###
DELETE https://localhost:5162/api/categorias/6