// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendnet.Data;

#nullable disable

namespace backendnet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculasPeliculaId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasCategoriaId", "PeliculasPeliculaId");

                    b.HasIndex("PeliculasPeliculaId");

                    b.ToTable("CategoriaPelicula");

                    b.HasData(
                        new
                        {
                            CategoriasCategoriaId = 6,
                            PeliculasPeliculaId = 1
                        },
                        new
                        {
                            CategoriasCategoriaId = 6,
                            PeliculasPeliculaId = 2
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 2
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 3
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 3
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 3
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 4
                        },
                        new
                        {
                            CategoriasCategoriaId = 6,
                            PeliculasPeliculaId = 5
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 5
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 6
                        },
                        new
                        {
                            CategoriasCategoriaId = 15,
                            PeliculasPeliculaId = 6
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 7
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 8
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 8
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 9
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 9
                        },
                        new
                        {
                            CategoriasCategoriaId = 10,
                            PeliculasPeliculaId = 9
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 10
                        },
                        new
                        {
                            CategoriasCategoriaId = 4,
                            PeliculasPeliculaId = 10
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 11
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 11
                        },
                        new
                        {
                            CategoriasCategoriaId = 4,
                            PeliculasPeliculaId = 11
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 12
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 12
                        },
                        new
                        {
                            CategoriasCategoriaId = 8,
                            PeliculasPeliculaId = 12
                        },
                        new
                        {
                            CategoriasCategoriaId = 1,
                            PeliculasPeliculaId = 13
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 13
                        },
                        new
                        {
                            CategoriasCategoriaId = 4,
                            PeliculasPeliculaId = 13
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 14
                        },
                        new
                        {
                            CategoriasCategoriaId = 4,
                            PeliculasPeliculaId = 14
                        },
                        new
                        {
                            CategoriasCategoriaId = 5,
                            PeliculasPeliculaId = 14
                        },
                        new
                        {
                            CategoriasCategoriaId = 2,
                            PeliculasPeliculaId = 15
                        },
                        new
                        {
                            CategoriasCategoriaId = 5,
                            PeliculasPeliculaId = 15
                        },
                        new
                        {
                            CategoriasCategoriaId = 10,
                            PeliculasPeliculaId = 15
                        });
                });

            modelBuilder.Entity("backendnet.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Protegida")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Acción",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Aventura",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Animación",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nombre = "Ciencia ficción",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nombre = "Comedia",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 6,
                            Nombre = "Crimen",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 7,
                            Nombre = "Documental",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 8,
                            Nombre = "Drama",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 9,
                            Nombre = "Familiar",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 10,
                            Nombre = "Fantasia",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 11,
                            Nombre = "Historia",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 12,
                            Nombre = "Horror",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 13,
                            Nombre = "Musica",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 14,
                            Nombre = "Misterio",
                            Protegida = true
                        },
                        new
                        {
                            CategoriaId = 15,
                            Nombre = "Romance",
                            Protegida = true
                        });
                });

            modelBuilder.Entity("backendnet.Models.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PeliculaId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PeliculaId");

                    b.ToTable("Pelicula");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "El banquero Andy Dufresne es arrestado por matar a su esposa y al amante de ella, y es condenado a cadena perpetua en la prisión de Shawshank. Allí entabla amistad con Red, un preso veterano que cumple condena desde hace mucho tiempo. Andy es el blanco de abusos y violaciones por parte de los guardias y de los presos, pero se gana el respeto de Red y de los demás reclusos al ayudarles con sus problemas fiscales.",
                            Titulo = "Sueño de fuga"
                        },
                        new
                        {
                            PeliculaId = 2,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Don Vito Corleone, conocido dentro de los círculos del hampa como El Padrino, es el patriarca de la familia Corleone. Después de que un intento fallido de asesinato en su contra lo deja gravemente herido, su hijo Michael se hace cargo de los negocios familiares. Michael, un veterano de guerra ajeno a los negocios de su padre, busca vengar el atentado contra su padre y se convierte en un líder implacable.",
                            Titulo = "El padrino"
                        },
                        new
                        {
                            PeliculaId = 3,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Batman, el comisario Gordon y el nuevo fiscal del distrito Harvey Dent unen fuerzas para acabar con el crimen organizado en Ciudad Gótica. Sin embargo, se encontrarán con un genio criminal conocido como Joker, que provocará el caos en la ciudad.",
                            Titulo = "El caballero oscuro"
                        },
                        new
                        {
                            PeliculaId = 4,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "La última parte de la trilogía de El Señor de los Anillos. La oscuridad se cierne sobre la Tierra Media. Después de que el oscuro señor Sauron ordenara a sus tropas que atacaran Minas Tirith, la capital de Gondor, el rey Theoden de Rohan reúne a sus aliados para ayudar a defender la ciudad fortificada. Mientras tanto, Frodo y Sam llevan el anillo a Mordor, la única esperanza para la supervivencia de la Tierra Media.",
                            Titulo = "El retorno del rey"
                        },
                        new
                        {
                            PeliculaId = 5,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "En Los Ángeles, en 1992, el crimen y la violencia se han apoderado de la ciudad. El exconvicto Lenny Nero vende un nuevo tipo de droga llamada SQUID, que permite a los usuarios experimentar los recuerdos y sensaciones de otras personas. Cuando una prostituta amiga suya es asesinada, Lenny se ve envuelto en una trama de corrupción y violencia.",
                            Titulo = "Tiempos violentos"
                        },
                        new
                        {
                            PeliculaId = 6,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Forrest Gump es un hombre con un coeficiente intelectual por debajo de la media, pero con una vida plena. A lo largo de su vida, Forrest se ve envuelto en situaciones históricas importantes, como la guerra de Vietnam y la lucha por los derechos civiles. A pesar de sus limitaciones, Forrest siempre se mantiene fiel a sus amigos y a sus ideales.",
                            Titulo = "Forest Gump"
                        },
                        new
                        {
                            PeliculaId = 7,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Un joven sin nombre y sin rumbo en la vida conoce a Tyler Durden, un vendedor de jabón con una filosofía muy particular. Juntos, crean un club de lucha clandestino que se convierte en un movimiento revolucionario. Sin embargo, la relación entre los dos se complica cuando conocen a Marla Singer, una mujer misteriosa que se convierte en el objeto de deseo de ambos.",
                            Titulo = "El club de la pelea"
                        },
                        new
                        {
                            PeliculaId = 8,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Dom Cobb es un ladrón de sueños que se dedica a robar secretos de la mente de las personas mientras duermen. Cuando se le ofrece la oportunidad de redimirse a cambio de una última misión, Cobb acepta el desafío de implantar una idea en la mente de un empresario rival. Sin embargo, la misión se complica cuando Cobb se enfrenta a sus propios demonios y a los secretos de su pasado.",
                            Titulo = "Inception"
                        },
                        new
                        {
                            PeliculaId = 9,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Después de la destrucción de la Estrella de la Muerte, la Alianza Rebelde se ha refugiado en el planeta Hoth. Mientras tanto, Darth Vader ha puesto en marcha un plan para capturar a Luke Skywalker y convertirlo en un Sith. Luke, Leia, Han Solo y Chewbacca se ven obligados a huir de Hoth y buscar refugio en la ciudad de las nubes, donde se enfrentarán a un enemigo inesperado.",
                            Titulo = "Star Wars Episodio V: El imperio contraataca"
                        },
                        new
                        {
                            PeliculaId = 10,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Thomas Anderson es un programador de software que lleva una doble vida como hacker informático conocido como Neo. Cuando es contactado por Morfeo, un misterioso líder de la resistencia, Neo descubre que el mundo en el que vive es una simulación creada por máquinas inteligentes. Morfeo le ofrece la oportunidad de unirse a la resistencia y luchar contra las máquinas, pero Neo deberá enfrentarse a sus propios miedos y dudas para convertirse en el Elegido.",
                            Titulo = "Matrix"
                        },
                        new
                        {
                            PeliculaId = 11,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "En un futuro distópico, la Tierra se está muriendo debido a la falta de recursos naturales. Un grupo de astronautas es enviado en una misión espacial para encontrar un nuevo planeta habitable para la humanidad. Sin embargo, la misión se complica cuando los astronautas se enfrentan a peligros desconocidos y a la traición de uno de sus miembros.",
                            Titulo = "Interestelar"
                        },
                        new
                        {
                            PeliculaId = 12,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "La segunda parte de la adaptación de la novela de ciencia ficción de Frank Herbert. Después de la traición de su tío, Paul Atreides se convierte en el líder de la tribu Fremen y se embarca en una misión para liberar el planeta Arrakis del control de la Casa Harkonnen. Sin embargo, Paul descubre que su destino está ligado a un antiguo profeta y a una misteriosa profecía que podría cambiar el curso de la historia.",
                            Titulo = "Dune: Parte dos"
                        },
                        new
                        {
                            PeliculaId = 13,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Después de la destrucción del T-800 en Los Ángeles, Sarah Connor y su hijo John se han escondido en México para evitar ser capturados por Skynet. Sin embargo, un nuevo Terminator, el T-1000, es enviado desde el futuro para eliminar a John. Sarah y John se unen a un T-800 reprogramado para protegerlos y juntos intentan detener el juicio final y salvar a la humanidad de la extinción.",
                            Titulo = "Terminator 2: El juicio final"
                        },
                        new
                        {
                            PeliculaId = 14,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Marty McFly es un adolescente de los años 80 que viaja en el tiempo a 1955 en un DeLorean modificado por el Dr. Emmett Brown. Allí, Marty conoce a sus padres antes de que se conozcan y cambia el curso de la historia. Ahora, Marty debe encontrar una forma de arreglar las cosas y regresar a su tiempo antes de que sea demasiado tarde.",
                            Titulo = "Volver al futuro"
                        },
                        new
                        {
                            PeliculaId = 15,
                            Anio = 0,
                            Poster = "N/A",
                            Sinopsis = "Vivir en Barbie Land es el sueño de muchas niñas. Barbie es una muñeca de plástico que ha sido un icono de la moda y la belleza desde su creación en 1959. Con su cabello rubio, su sonrisa perfecta y su guardarropa interminable, Barbie ha inspirado a generaciones de niñas a soñar en grande y a creer en sí mismas.",
                            Titulo = "Barbie"
                        });
                });

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.HasOne("backendnet.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendnet.Models.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasPeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
